"""create blog table

Revision ID: 29795ec2e686
Revises: be0c40c155a1
Create Date: 2026-01-29 12:22:07.997242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '29795ec2e686'
down_revision: Union[str, Sequence[str], None] = 'be0c40c155a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('blog', sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('blog', sa.Column('author_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('blog', sa.Column('blog_img_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'blog', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blog', type_='foreignkey')
    op.drop_column('blog', 'blog_img_url')
    op.drop_column('blog', 'author_id')
    op.drop_column('blog', 'content')
    op.drop_column('blog', 'title')
    # ### end Alembic commands ###
